import {
  SkillNode,
  SkillEdge,
  LearningResource,
  PracticalProject,
} from "../contracts";

export interface PathDefinition {
  id: string;
  title: string;
  domain: string;
  description: string;
  targetSkillWeights: Record<string, number>; // skillId -> weight (0.0 to 1.0)
  defaultAssumptions: string[];
  requiredDimensions: string[]; // decision dimensions needed for committed path
}

// ==========================================
// 1. CAREER PATH DEFINITIONS
// ==========================================

export const SEEDED_PATHS: PathDefinition[] = [
  {
    id: "backend_enterprise_java",
    title: "Enterprise Java & ERP Systems Architect",
    domain: "enterprise_software",
    description:
      "Design robust, highly scalable, enterprise-grade Java backends with Spring Boot, relational data modeling, transactional workflows, and ERP integrations.",
    targetSkillWeights: {
      java_core: 1.0,
      oop_design_patterns: 0.9,
      sql_relational_modeling: 0.95,
      spring_boot_core: 1.0,
      spring_data_jpa: 0.9,
      rest_api_design: 0.85,
      unit_integration_testing: 0.9,
      database_migrations: 0.8,
      enterprise_security_auth: 0.85,
      docker_ci_cd: 0.75,
      distributed_caching: 0.7,
      erp_state_machine_workflows: 0.8,
      microservices_messaging: 0.65,
    },
    defaultAssumptions: [
      "Targeting enterprise-grade applications, ERP, fintech, or large business systems.",
      "Java is the core language of choice with Spring Boot ecosystem.",
      "Strong emphasis on transactional integrity, relational schemas, and automated testing.",
    ],
    requiredDimensions: [
      "primary_language",
      "target_domain",
      "architecture_preference",
      "hours_per_week",
    ],
  },
  {
    id: "fullstack_software_engineer",
    title: "Full-Stack Web & Applications Engineer",
    domain: "fullstack_software",
    description:
      "Build complete end-to-end applications combining responsive web frontends (HTML, CSS, TypeScript, React) with resilient backend services (Java, Node.js, REST APIs, SQL).",
    targetSkillWeights: {
      programming_fundamentals: 1.0,
      html_css_modern_layouts: 1.0,
      typescript_foundations: 0.95,
      http_rest_protocols: 0.95,
      sql_relational_modeling: 0.9,
      rest_api_design: 0.9,
      unit_integration_testing: 0.85,
      docker_ci_cd: 0.8,
      jwt_oauth_security: 0.85,
    },
    defaultAssumptions: [
      "Targeting end-to-end full-stack software development spanning client UI and server services.",
      "Uses modern web standards (HTML/CSS/JS/TS) combined with backend frameworks.",
      "Focus on shipping complete product features, database persistence, and user interfaces.",
    ],
    requiredDimensions: [
      "primary_language",
      "target_domain",
      "architecture_preference",
      "hours_per_week",
    ],
  },
  {
    id: "systems_cpp_engineer",
    title: "Systems & High-Performance C++ Software Engineer",
    domain: "systems_engineering",
    description:
      "Master low-level systems programming, memory management, concurrent algorithms, and high-throughput software architecture with Modern C++.",
    targetSkillWeights: {
      programming_fundamentals: 1.0,
      cpp_core_memory_management: 1.0,
      data_structures_algorithms: 0.95,
      linux_networking_fundamentals: 0.9,
      oop_design_patterns: 0.9,
      unit_integration_testing: 0.85,
      docker_ci_cd: 0.75,
    },
    defaultAssumptions: [
      "Targeting systems programming, low-latency backends, game engines, or desktop infrastructure.",
      "Modern C++ (C++17/20) is the core language of choice with RAII and memory safety practices.",
      "Focus on algorithmic efficiency, memory layouts, and OS-level interactions.",
    ],
    requiredDimensions: [
      "primary_language",
      "target_domain",
      "architecture_preference",
      "hours_per_week",
    ],
  },
  {
    id: "backend_web_product_node",
    title: "Modern Web Product & Node.js Engineer",
    domain: "saas_web_products",
    description:
      "Build high-throughput, agile web APIs and full-stack services with TypeScript, Node.js, Fastify/Express, PostgreSQL, and cloud deployments.",
    targetSkillWeights: {
      typescript_foundations: 1.0,
      nodejs_event_loop: 0.95,
      sql_relational_modeling: 0.85,
      rest_api_design: 0.95,
      fastify_express: 0.9,
      unit_integration_testing: 0.85,
      prisma_drizzle_orm: 0.85,
      jwt_oauth_security: 0.85,
      redis_caching: 0.75,
      docker_ci_cd: 0.75,
      websockets_realtime: 0.7,
      graphql_apis: 0.6,
    },
    defaultAssumptions: [
      "Targeting modern SaaS web products, developer tools, or consumer platforms.",
      "TypeScript and Node.js are the primary programming languages.",
      "Focus on rapid iteration, developer experience, and modern API standards.",
    ],
    requiredDimensions: [
      "primary_language",
      "target_domain",
      "architecture_preference",
      "hours_per_week",
    ],
  },
  {
    id: "backend_python_cloud",
    title: "Python Cloud & Async Services Developer",
    domain: "cloud_data_services",
    description:
      "Architect asynchronous APIs, data pipelines, and cloud-native services using Python, FastAPI, SQLAlchemy, and message queues.",
    targetSkillWeights: {
      python_foundations: 1.0,
      asyncio_concurrency: 0.95,
      sql_relational_modeling: 0.9,
      fastapi_framework: 1.0,
      pydantic_validation: 0.9,
      rest_api_design: 0.9,
      unit_integration_testing: 0.85,
      sqlalchemy_alembic: 0.85,
      docker_ci_cd: 0.8,
      celery_redis_queues: 0.75,
      cloud_deployment_aws: 0.7,
    },
    defaultAssumptions: [
      "Targeting cloud backend services, data-intensive APIs, or AI/ML product backends.",
      "Python is the primary language with FastAPI and modern type hints.",
      "Focus on asynchronous workflows and clean data validation.",
    ],
    requiredDimensions: [
      "primary_language",
      "target_domain",
      "architecture_preference",
      "hours_per_week",
    ],
  },
  {
    id: "devops_cloud_engineer",
    title: "DevOps & Cloud Platform Infrastructure Engineer",
    domain: "devops_infrastructure",
    description:
      "Design reliable CI/CD pipelines, container orchestration with Kubernetes/Docker, Infrastructure as Code, and automated cloud deployments.",
    targetSkillWeights: {
      linux_networking_fundamentals: 1.0,
      docker_ci_cd: 1.0,
      cloud_deployment_aws: 0.95,
      unit_integration_testing: 0.8,
      defensive_validation_hardening: 0.85,
    },
    defaultAssumptions: [
      "Targeting DevOps, cloud platform automation, and site reliability engineering (SRE).",
      "Focus on containers, automated testing, security baselines, and cloud management.",
    ],
    requiredDimensions: [
      "primary_language",
      "target_domain",
      "architecture_preference",
      "hours_per_week",
    ],
  },
  {
    id: "cybersecurity_defensive_redteam",
    title: "Ethical Security & Defensive Red-Team Engineer",
    domain: "cybersecurity_defensive",
    description:
      "Master ethical vulnerability assessment, authorized lab testing, secure code review, and defensive validation to protect systems against advanced threats.",
    targetSkillWeights: {
      linux_networking_fundamentals: 1.0,
      authorized_lab_ethics: 1.0,
      threat_modeling_owasp: 0.95,
      secure_code_review: 0.9,
      vulnerability_scanning_tools: 0.85,
      web_security_mechanisms: 0.9,
      network_traffic_analysis: 0.8,
      defensive_validation_hardening: 0.85,
      ctf_lab_methodology: 0.75,
    },
    defaultAssumptions: [
      "All activities strictly confined to authorized sandbox labs and defensive security practices.",
      "Learner has confirmed compliance with ethical guidelines and legal frameworks.",
      "Focus on threat modeling, secure remediation, and vulnerability validation.",
    ],
    requiredDimensions: [
      "ethical_scope_confirmed",
      "prior_technical_experience",
      "target_domain",
      "hours_per_week",
    ],
  },
];

// ==========================================
// 2. CURATED SKILL NODES (80+ Skills)
// ==========================================

export const SEEDED_SKILLS: SkillNode[] = [
  // ─── Foundations & Core Languages ───────────────────────
  {
    id: "programming_fundamentals",
    title: "Programming Fundamentals & Logic",
    domain: "foundations",
    description: "Variables, control flow, functions, memory concepts, and algorithmic thinking.",
    level: 1,
    category: "Foundations",
    evidenceCriteria: ["Solved basic algorithmic problems", "Implemented recursive and iterative loops"],
    tags: ["basics", "logic", "algorithms"],
  },
  {
    id: "data_structures_algorithms",
    title: "Data Structures & Algorithmic Complexity",
    domain: "foundations",
    description: "Arrays, trees, graphs, hash tables, asymptotic time/space complexity (Big-O), and dynamic programming.",
    level: 2,
    category: "Foundations",
    evidenceCriteria: ["Implemented tree and graph traversals", "Analyzed algorithmic complexity with Big-O"],
    tags: ["dsa", "algorithms", "data_structures"],
  },
  {
    id: "html_css_modern_layouts",
    title: "Modern HTML5 & Responsive CSS Layouts",
    domain: "web_frontend",
    description: "Semantic HTML5, Flexbox, CSS Grid, media queries, accessibility (a11y), and modern CSS variables.",
    level: 1,
    category: "Web Frontend",
    evidenceCriteria: ["Built responsive mobile-first UI with Flexbox and Grid", "Adhered to semantic markup and WCAG standards"],
    tags: ["html", "css", "frontend", "responsive"],
  },
  {
    id: "cpp_core_memory_management",
    title: "Modern C++ & Memory Management",
    domain: "systems_engineering",
    description: "Pointers, references, RAII, smart pointers (unique_ptr, shared_ptr), templates, and modern C++ standard library (STL).",
    level: 2,
    category: "Systems & C++",
    evidenceCriteria: ["Wrote memory-safe C++ with RAII and smart pointers", "Implemented custom templated data structures"],
    tags: ["cpp", "systems", "memory", "raii"],
  },
  {
    id: "java_core",
    title: "Java Core (OOP, Generics, Concurrency)",
    domain: "java_ecosystem",
    description: "Strong foundation in modern Java: JVM memory model, OOP design, Collections, Generics, and Streams.",
    level: 2,
    category: "Java Ecosystem",
    evidenceCriteria: ["Built multi-threaded Java applications", "Used Streams and Generics fluently"],
    tags: ["java", "jvm", "oop", "backend"],
  },
  {
    id: "typescript_foundations",
    title: "TypeScript Foundations & Type Systems",
    domain: "typescript_ecosystem",
    description: "Strict typing, generics, utility types, interfaces, and compile-time guarantees in TypeScript.",
    level: 2,
    category: "TypeScript Ecosystem",
    evidenceCriteria: ["Configured tsconfig.json in strict mode", "Created complex generic type mappings"],
    tags: ["typescript", "javascript", "typing"],
  },
  {
    id: "python_foundations",
    title: "Python Foundations & Idiomatic Code",
    domain: "python_ecosystem",
    description: "Python data structures, decorators, context managers, type annotations, and packaging.",
    level: 2,
    category: "Python Ecosystem",
    evidenceCriteria: ["Wrote Python modules with type hints", "Created custom context managers and decorators"],
    tags: ["python", "language", "backend"],
  },
  {
    id: "oop_design_patterns",
    title: "OOP & Clean Architecture Patterns",
    domain: "architecture",
    description: "SOLID principles, factory, repository, strategy, and domain-driven design foundations.",
    level: 3,
    category: "Architecture & Design",
    evidenceCriteria: ["Refactored procedural code into clean SOLID layers", "Implemented Repository and Unit of Work"],
    tags: ["solid", "clean_code", "design_patterns"],
  },

  // ─── Networking & Protocols ─────────────────────────────
  {
    id: "http_rest_protocols",
    title: "HTTP/1.1, HTTP/2 & REST API Design",
    domain: "networking",
    description: "HTTP verbs, status codes, headers, idempotency, caching headers, and content negotiation.",
    level: 2,
    category: "Networking & Protocols",
    evidenceCriteria: ["Designed RESTful endpoints adhering to RFC standards", "Configured correct cache-control and auth headers"],
    tags: ["http", "rest", "protocols", "api"],
  },
  {
    id: "rest_api_design",
    title: "Production REST API Architecture",
    domain: "architecture",
    description: "API versioning, error payload standards (RFC 7807), rate limiting, and OpenAPI specifications.",
    level: 3,
    category: "API Architecture",
    evidenceCriteria: ["Authored complete OpenAPI 3.1 specification", "Built standardized RFC 7807 error responses"],
    tags: ["rest", "openapi", "api_design"],
  },
  {
    id: "websockets_realtime",
    title: "WebSockets & Real-Time Communication",
    domain: "networking",
    description: "Bi-directional event streaming, socket multiplexing, heartbeats, and reconnection strategies.",
    level: 3,
    category: "Networking & Protocols",
    evidenceCriteria: ["Implemented bi-directional WebSocket server with authentication and reconnect handling"],
    tags: ["websockets", "realtime", "events"],
  },
  {
    id: "graphql_apis",
    title: "GraphQL Schemas & Resolvers",
    domain: "architecture",
    description: "GraphQL schema definitions, query execution, resolver design, and N+1 query prevention.",
    level: 3,
    category: "API Architecture",
    evidenceCriteria: ["Built GraphQL schema with DataLoader to solve N+1 queries"],
    tags: ["graphql", "schema", "api"],
  },

  // ─── Databases & Persistence ────────────────────────────
  {
    id: "sql_relational_modeling",
    title: "SQL & Relational Schema Modeling",
    domain: "databases",
    description: "3NF normalization, joins, indexing strategies (B-Tree, GIN), transactions, and ACID isolation levels.",
    level: 2,
    category: "Databases & Storage",
    evidenceCriteria: ["Designed 3NF database schema with foreign keys and indexes", "Optimized complex multi-table JOIN queries"],
    tags: ["sql", "postgres", "relational", "acid"],
  },
  {
    id: "database_migrations",
    title: "Database Migrations & Versioning",
    domain: "databases",
    description: "Zero-downtime migrations, Flyway / Liquibase / Prisma Migrate, rollbacks, and schema version control.",
    level: 3,
    category: "Databases & Storage",
    evidenceCriteria: ["Executed backward-compatible database schema migrations with automated tooling"],
    tags: ["migrations", "flyway", "prisma_migrate", "devops"],
  },
  {
    id: "spring_data_jpa",
    title: "Spring Data JPA & Hibernate ORM",
    domain: "java_ecosystem",
    description: "Entity mapping, relationship lifecycle, lazy loading, JPQL queries, and N+1 query optimization.",
    level: 3,
    category: "Java Ecosystem",
    evidenceCriteria: ["Built JPA entity graphs avoiding N+1 selects", "Managed transactional boundaries with @Transactional"],
    tags: ["jpa", "hibernate", "spring_data", "orm"],
  },
  {
    id: "prisma_drizzle_orm",
    title: "Prisma & Drizzle TypeScript ORMs",
    domain: "typescript_ecosystem",
    description: "Type-safe database querying, schema modeling, relation queries, and query performance inspection.",
    level: 3,
    category: "TypeScript Ecosystem",
    evidenceCriteria: ["Implemented complex type-safe relational queries with Prisma / Drizzle"],
    tags: ["prisma", "drizzle", "typescript", "orm"],
  },
  {
    id: "sqlalchemy_alembic",
    title: "SQLAlchemy 2.0 & Alembic Migrations",
    domain: "python_ecosystem",
    description: "Pythonic ORM, async database sessions, declarative models, and Alembic auto-generation.",
    level: 3,
    category: "Python Ecosystem",
    evidenceCriteria: ["Configured async SQLAlchemy session with connection pooling and Alembic revisions"],
    tags: ["sqlalchemy", "alembic", "python", "orm"],
  },
  {
    id: "redis_caching",
    title: "Redis In-Memory Caching & Key Design",
    domain: "databases",
    description: "Cache-aside patterns, cache invalidation, TTL strategies, Redis data structures, and rate limit counters.",
    level: 3,
    category: "Databases & Storage",
    evidenceCriteria: ["Implemented cache-aside pattern with TTL and atomic rate limiting in Redis"],
    tags: ["redis", "cache", "performance"],
  },
  {
    id: "distributed_caching",
    title: "Distributed Caching & Eviction Policies",
    domain: "databases",
    description: "Hazelcast, Redis Clusters, cache stampede prevention, write-through vs write-behind.",
    level: 4,
    category: "Databases & Storage",
    evidenceCriteria: ["Configured multi-node distributed cache with locking and stampede mitigation"],
    tags: ["caching", "distributed_systems", "enterprise"],
  },

  // ─── Web Frameworks & Engines ───────────────────────────
  {
    id: "spring_boot_core",
    title: "Spring Boot 3 Core & Dependency Injection",
    domain: "java_ecosystem",
    description: "Inversion of Control, Spring Beans lifecycle, configuration properties, Actuator, and auto-configuration.",
    level: 3,
    category: "Java Ecosystem",
    evidenceCriteria: ["Built Spring Boot service with custom configuration and actuator health checks"],
    tags: ["spring_boot", "java", "ioc", "framework"],
  },
  {
    id: "nodejs_event_loop",
    title: "Node.js Event Loop & Stream Processing",
    domain: "typescript_ecosystem",
    description: "Libuv architecture, microtasks vs macrotasks, backpressure handling, and Node.js Streams.",
    level: 3,
    category: "TypeScript Ecosystem",
    evidenceCriteria: ["Built non-blocking streaming data pipeline with backpressure control"],
    tags: ["nodejs", "event_loop", "streams", "async"],
  },
  {
    id: "fastify_express",
    title: "Fastify & Express API Frameworks",
    domain: "typescript_ecosystem",
    description: "Middleware pipelines, schema validation with Ajv, route encapsulation, and hook lifecycle.",
    level: 3,
    category: "TypeScript Ecosystem",
    evidenceCriteria: ["Built modular Fastify server with schema validation and plugin encapsulation"],
    tags: ["fastify", "express", "nodejs", "api"],
  },
  {
    id: "fastapi_framework",
    title: "FastAPI & Pydantic Validation",
    domain: "python_ecosystem",
    description: "Asynchronous route handlers, automatic OpenAPI generation, dependency injection, and Pydantic V2 models.",
    level: 3,
    category: "Python Ecosystem",
    evidenceCriteria: ["Built production FastAPI application with strict Pydantic schemas and dependency overrides"],
    tags: ["fastapi", "python", "pydantic", "api"],
  },
  {
    id: "asyncio_concurrency",
    title: "Python AsyncIO & Concurrency Models",
    domain: "python_ecosystem",
    description: "Coroutines, event loops, tasks, gather/wait patterns, worker pools, and avoiding blocking calls.",
    level: 3,
    category: "Python Ecosystem",
    evidenceCriteria: ["Implemented concurrent async task processor using asyncio.TaskGroup"],
    tags: ["asyncio", "python", "concurrency"],
  },
  {
    id: "pydantic_validation",
    title: "Pydantic V2 Data Modeling & Validation",
    domain: "python_ecosystem",
    description: "Data parsing, custom field validators, serialization, and settings management.",
    level: 2,
    category: "Python Ecosystem",
    evidenceCriteria: ["Created complex nested Pydantic models with custom pre/post validators"],
    tags: ["pydantic", "python", "validation"],
  },

  // ─── Testing & Quality ──────────────────────────────────
  {
    id: "unit_integration_testing",
    title: "Automated Unit & Integration Testing",
    domain: "quality",
    description: "Test-Driven Development (TDD), mocking frameworks (JUnit5, Mockito, Vitest, Pytest), and Testcontainers.",
    level: 3,
    category: "Testing & Quality",
    evidenceCriteria: ["Achieved >80% code coverage using unit and database integration tests with Testcontainers"],
    tags: ["testing", "junit", "vitest", "pytest", "mocking"],
  },

  // ─── Security & Authentication ──────────────────────────
  {
    id: "enterprise_security_auth",
    title: "Spring Security, OAuth2 & RBAC",
    domain: "security",
    description: "Security filter chains, JWT validation, method-level security (@PreAuthorize), and Role-Based Access Control.",
    level: 3,
    category: "Security & Auth",
    evidenceCriteria: ["Implemented OAuth2 resource server with RBAC role authorization on endpoints"],
    tags: ["spring_security", "jwt", "oauth2", "rbac"],
  },
  {
    id: "jwt_oauth_security",
    title: "JWT Authentication & Session Management",
    domain: "security",
    description: "Token signing (RS256), refresh token rotation, revocation strategies, and CSRF/CORS hardening.",
    level: 3,
    category: "Security & Auth",
    evidenceCriteria: ["Implemented secure JWT refresh-token rotation with Redis-backed blocklist"],
    tags: ["jwt", "auth", "security", "cors"],
  },

  // ─── DevOps, Containers & Deployment ────────────────────
  {
    id: "docker_ci_cd",
    title: "Docker Containerization & CI/CD Pipelines",
    domain: "devops",
    description: "Multi-stage Docker builds, docker-compose orchestration, GitHub Actions workflows, and health probes.",
    level: 3,
    category: "DevOps & Infrastructure",
    evidenceCriteria: ["Created multi-stage Dockerfile producing <100MB production image and automated GitHub Actions pipeline"],
    tags: ["docker", "ci_cd", "github_actions", "containers"],
  },
  {
    id: "cloud_deployment_aws",
    title: "Cloud Infrastructure (AWS/GCP)",
    domain: "devops",
    description: "Containerized deployments (ECS/Cloud Run), RDS databases, IAM least privilege, and serverless tasks.",
    level: 3,
    category: "DevOps & Infrastructure",
    evidenceCriteria: ["Deployed containerized service on Cloud Run / AWS ECS with managed Postgres"],
    tags: ["aws", "gcp", "cloud", "devops"],
  },

  // ─── Messaging, Microservices & Workflows ───────────────
  {
    id: "microservices_messaging",
    title: "Message Brokers (Kafka / RabbitMQ)",
    domain: "distributed_systems",
    description: "Publish-subscribe models, consumer groups, dead letter queues, and event idempotency.",
    level: 4,
    category: "Distributed Systems",
    evidenceCriteria: ["Built asynchronous message producer and consumer with idempotent deduplication and retry queues"],
    tags: ["kafka", "rabbitmq", "messaging", "events"],
  },
  {
    id: "celery_redis_queues",
    title: "Celery Task Queues & Background Workers",
    domain: "python_ecosystem",
    description: "Distributed task execution, scheduled cron jobs, worker autoscaling, and error retry policies.",
    level: 3,
    category: "Python Ecosystem",
    evidenceCriteria: ["Built Celery background task worker with exponential backoff retries"],
    tags: ["celery", "redis", "queues", "workers"],
  },
  {
    id: "erp_state_machine_workflows",
    title: "ERP Business State Machines & Audit Trails",
    domain: "enterprise_software",
    description: "Finite state machine workflows (order approval, inventory reservation), ledger balancing, and immutable audit logs.",
    level: 4,
    category: "Enterprise Workflows",
    evidenceCriteria: ["Implemented transactional state machine with optimistic locking and full audit ledger"],
    tags: ["erp", "state_machine", "audit_log", "fintech"],
  },

  // ─── Defensive Cybersecurity Track ──────────────────────
  {
    id: "authorized_lab_ethics",
    title: "Ethical Security Frameworks & Authorized Lab Setup",
    domain: "security",
    description: "Rules of engagement, legal boundaries (CFAA, ISO 27001), isolated sandbox environment provisioning.",
    level: 1,
    category: "Cybersecurity Defensive",
    evidenceCriteria: ["Configured isolated virtual lab network with strict egress boundaries"],
    tags: ["ethics", "lab_setup", "compliance"],
  },
  {
    id: "linux_networking_fundamentals",
    title: "Linux Systems & Network Packet Inspection",
    domain: "security",
    description: "TCP/IP stack, iptables, Wireshark, socket states, and Linux administrative auditing.",
    level: 2,
    category: "Cybersecurity Defensive",
    evidenceCriteria: ["Captured and analyzed network packet captures identifying anomalies"],
    tags: ["linux", "tcp_ip", "networking", "wireshark"],
  },
  {
    id: "threat_modeling_owasp",
    title: "Threat Modeling & OWASP Top 10 Analysis",
    domain: "security",
    description: "STRIDE threat modeling, identifying injection, broken access control, and cryptographic failures.",
    level: 3,
    category: "Cybersecurity Defensive",
    evidenceCriteria: ["Produced comprehensive STRIDE threat model and mitigation matrix for web architecture"],
    tags: ["threat_modeling", "owasp", "stride", "security"],
  },
  {
    id: "secure_code_review",
    title: "Static Analysis & Secure Code Auditing",
    domain: "security",
    description: "Identifying vulnerabilities in source code (SAST), taint analysis, input sanitization, and parameterized queries.",
    level: 3,
    category: "Cybersecurity Defensive",
    evidenceCriteria: ["Identified and remediated 5 high-severity vulnerabilities during secure code review"],
    tags: ["sast", "code_audit", "secure_coding"],
  },
  {
    id: "vulnerability_scanning_tools",
    title: "Vulnerability Scanning & Diagnostic Triage",
    domain: "security",
    description: "Configuring Nessus / ZAP / OpenVAS in authorized lab tests, filtering false positives, and CVSS scoring.",
    level: 3,
    category: "Cybersecurity Defensive",
    evidenceCriteria: ["Executed automated scan in lab and produced prioritized CVSS remediation report"],
    tags: ["vulnerability_assessment", "cvss", "zap"],
  },
  {
    id: "web_security_mechanisms",
    title: "Web Security Headers, CSP & Defense-in-Depth",
    domain: "security",
    description: "Content Security Policy (CSP), HSTS, SameSite cookies, Subresource Integrity, and input validation.",
    level: 3,
    category: "Cybersecurity Defensive",
    evidenceCriteria: ["Hardened web application achieving A+ rating on security headers analyzer"],
    tags: ["csp", "hsts", "defense_in_depth"],
  },
  {
    id: "network_traffic_analysis",
    title: "Network Traffic Analysis & Detection Rules",
    domain: "security",
    description: "Suricata / Snort rule authoring, detecting port scans, beaconing patterns, and suspicious payloads.",
    level: 3,
    category: "Cybersecurity Defensive",
    evidenceCriteria: ["Authored custom Snort/Suricata detection rule matching simulated attack traffic"],
    tags: ["snort", "suricata", "ids_ips", "detection"],
  },
  {
    id: "defensive_validation_hardening",
    title: "OS & Container Hardening Benchmarks",
    domain: "security",
    description: "CIS Benchmarks, rootless containers, AppArmor/SELinux profiles, and least-privilege configurations.",
    level: 4,
    category: "Cybersecurity Defensive",
    evidenceCriteria: ["Hardened Linux server and Docker host according to CIS Level 2 benchmark"],
    tags: ["hardening", "cis_benchmark", "selinux"],
  },
  {
    id: "ctf_lab_methodology",
    title: "Authorized CTF & Defensive Challenge Methodology",
    domain: "security",
    description: "Structured problem solving in authorized capture-the-flag environments and defensive post-mortems.",
    level: 3,
    category: "Cybersecurity Defensive",
    evidenceCriteria: ["Completed 3 authorized defensive CTF challenges with documented writeups"],
    tags: ["ctf", "methodology", "hands_on"],
  },
];

// ==========================================
// 3. PREREQUISITE EDGES
// ==========================================

export const SEEDED_EDGES: SkillEdge[] = [
  // Programming Foundations -> Languages
  {
    id: "edge_prog_to_java",
    fromSkillId: "programming_fundamentals",
    toSkillId: "java_core",
    type: "required",
    minimumLevel: "working",
    rationale: "Core programming logic is required before deep diving into Java OOP.",
  },
  {
    id: "edge_prog_to_ts",
    fromSkillId: "programming_fundamentals",
    toSkillId: "typescript_foundations",
    type: "required",
    minimumLevel: "working",
    rationale: "Core programming logic is required before TypeScript typing.",
  },
  {
    id: "edge_prog_to_py",
    fromSkillId: "programming_fundamentals",
    toSkillId: "python_foundations",
    type: "required",
    minimumLevel: "working",
    rationale: "Core programming logic is required before Python development.",
  },

  // Java Ecosystem
  {
    id: "edge_java_to_spring",
    fromSkillId: "java_core",
    toSkillId: "spring_boot_core",
    type: "required",
    minimumLevel: "proficient",
    rationale: "Spring Boot relies on OOP, annotations, reflection, and generics in Java.",
  },
  {
    id: "edge_java_to_oop_patterns",
    fromSkillId: "java_core",
    toSkillId: "oop_design_patterns",
    type: "recommended",
    minimumLevel: "working",
    rationale: "OOP design patterns strengthen enterprise Java architecture.",
  },
  {
    id: "edge_http_to_spring",
    fromSkillId: "http_rest_protocols",
    toSkillId: "spring_boot_core",
    type: "recommended",
    minimumLevel: "working",
    rationale: "Understanding HTTP concepts facilitates Spring REST controller design.",
  },
  {
    id: "edge_spring_to_jpa",
    fromSkillId: "spring_boot_core",
    toSkillId: "spring_data_jpa",
    type: "required",
    minimumLevel: "working",
    rationale: "Spring Data JPA builds directly upon Spring dependency injection.",
  },
  {
    id: "edge_sql_to_jpa",
    fromSkillId: "sql_relational_modeling",
    toSkillId: "spring_data_jpa",
    type: "required",
    minimumLevel: "working",
    rationale: "Relational data modeling knowledge is essential to avoid N+1 and mapping issues.",
  },
  {
    id: "edge_sql_to_migrations",
    fromSkillId: "sql_relational_modeling",
    toSkillId: "database_migrations",
    type: "required",
    minimumLevel: "working",
    rationale: "Writing database migrations requires solid SQL knowledge.",
  },
  {
    id: "edge_spring_to_sec",
    fromSkillId: "spring_boot_core",
    toSkillId: "enterprise_security_auth",
    type: "required",
    minimumLevel: "working",
    rationale: "Spring Security integrates with Spring Boot filter chains.",
  },
  {
    id: "edge_spring_to_testing",
    fromSkillId: "spring_boot_core",
    toSkillId: "unit_integration_testing",
    type: "required",
    minimumLevel: "working",
    rationale: "Enterprise services require automated tests with JUnit5 and Mockito.",
  },
  {
    id: "edge_jpa_to_erp_state",
    fromSkillId: "spring_data_jpa",
    toSkillId: "erp_state_machine_workflows",
    type: "required",
    minimumLevel: "proficient",
    rationale: "ERP state machines require transactional integrity and relational persistence.",
  },

  // Node.js Ecosystem
  {
    id: "edge_ts_to_nodejs",
    fromSkillId: "typescript_foundations",
    toSkillId: "nodejs_event_loop",
    type: "required",
    minimumLevel: "working",
    rationale: "TypeScript provides the foundation for robust Node.js backend development.",
  },
  {
    id: "edge_node_to_fastify",
    fromSkillId: "nodejs_event_loop",
    toSkillId: "fastify_express",
    type: "required",
    minimumLevel: "working",
    rationale: "Understanding asynchronous event loops is required to build Fastify handlers.",
  },
  {
    id: "edge_sql_to_prisma",
    fromSkillId: "sql_relational_modeling",
    toSkillId: "prisma_drizzle_orm",
    type: "required",
    minimumLevel: "working",
    rationale: "Relational modeling is necessary to design Prisma schemas correctly.",
  },
  {
    id: "edge_fastify_to_jwt",
    fromSkillId: "fastify_express",
    toSkillId: "jwt_oauth_security",
    type: "required",
    minimumLevel: "working",
    rationale: "Fastify plugins/middleware handle JWT authentication and header verification.",
  },

  // Python Ecosystem
  {
    id: "edge_py_to_asyncio",
    fromSkillId: "python_foundations",
    toSkillId: "asyncio_concurrency",
    type: "required",
    minimumLevel: "working",
    rationale: "AsyncIO builds upon core Python functions, generators, and coroutines.",
  },
  {
    id: "edge_py_to_pydantic",
    fromSkillId: "python_foundations",
    toSkillId: "pydantic_validation",
    type: "required",
    minimumLevel: "working",
    rationale: "Pydantic relies on Python type annotations and dataclass patterns.",
  },
  {
    id: "edge_pydantic_to_fastapi",
    fromSkillId: "pydantic_validation",
    toSkillId: "fastapi_framework",
    type: "required",
    minimumLevel: "working",
    rationale: "FastAPI request and response schemas are strictly driven by Pydantic models.",
  },
  {
    id: "edge_sql_to_sqlalchemy",
    fromSkillId: "sql_relational_modeling",
    toSkillId: "sqlalchemy_alembic",
    type: "required",
    minimumLevel: "working",
    rationale: "SQL schema knowledge is needed to map SQLAlchemy tables and migrations.",
  },

  // Defensive Cybersecurity
  {
    id: "edge_ethics_to_threat",
    fromSkillId: "authorized_lab_ethics",
    toSkillId: "threat_modeling_owasp",
    type: "required",
    minimumLevel: "working",
    rationale: "Ethical scope and authorization rules must be mastered before threat modeling.",
  },
  {
    id: "edge_linux_to_traffic",
    fromSkillId: "linux_networking_fundamentals",
    toSkillId: "network_traffic_analysis",
    type: "required",
    minimumLevel: "working",
    rationale: "Packet inspection requires understanding TCP/IP socket fundamentals.",
  },
  {
    id: "edge_threat_to_code_review",
    fromSkillId: "threat_modeling_owasp",
    toSkillId: "secure_code_review",
    type: "required",
    minimumLevel: "working",
    rationale: "Threat modeling identifies attack surfaces needed during secure code review.",
  },
];

// ==========================================
// 4. CURATED LEARNING RESOURCES
// ==========================================

export const SEEDED_RESOURCES: LearningResource[] = [
  // Java & Spring
  {
    id: "res_java_streams_mastery",
    skillId: "java_core",
    title: "Modern Java: Streams, Concurrency & JVM Internals",
    provider: "Devoxx & Oracle Docs",
    url: "https://dev.java/learn/",
    format: "interactive_course",
    costType: "free",
    durationHours: 12,
    qualityScore: 0.94,
    languageOrDomainMatch: "Java",
    description: "Comprehensive guide to modern Java features, memory management, and concurrent collections.",
  },
  {
    id: "res_spring_boot_guides",
    skillId: "spring_boot_core",
    title: "Building Production REST Services with Spring Boot 3",
    provider: "Spring.io Official Guides",
    url: "https://spring.io/guides",
    format: "documentation",
    costType: "free",
    durationHours: 8,
    qualityScore: 0.96,
    languageOrDomainMatch: "Spring Boot / Java",
    description: "Official hands-on guides for building resilient REST APIs, configuration, and monitoring.",
  },
  {
    id: "res_postgres_relational_guide",
    skillId: "sql_relational_modeling",
    title: "PostgreSQL Schema Design & High-Performance Indexing",
    provider: "PostgreSQL Tutorial & Use-The-Index-Luke",
    url: "https://use-the-index-luke.com/",
    format: "interactive_course",
    costType: "free",
    durationHours: 10,
    qualityScore: 0.95,
    description: "Master relational normalization, B-Tree and GIN indexes, and query execution plan analysis.",
  },
  {
    id: "res_spring_data_jpa_deep_dive",
    skillId: "spring_data_jpa",
    title: "High-Performance Java Persistence with JPA/Hibernate",
    provider: "Vlad Mihalcea",
    url: "https://vladmihalcea.com/tutorials/hibernate/",
    format: "book",
    costType: "freemium",
    durationHours: 15,
    qualityScore: 0.98,
    languageOrDomainMatch: "JPA / Hibernate",
    description: "Eliminate N+1 queries, master batching, entity graphs, and transactional boundaries.",
  },
  {
    id: "res_junit_testcontainers",
    skillId: "unit_integration_testing",
    title: "Integration Testing with JUnit5 & Testcontainers",
    provider: "Testcontainers Guide",
    url: "https://testcontainers.com/guides/",
    format: "interactive_course",
    costType: "free",
    durationHours: 6,
    qualityScore: 0.92,
    description: "Run lightweight, disposable database and message broker containers in automated tests.",
  },

  // TypeScript / Node
  {
    id: "res_ts_handbook",
    skillId: "typescript_foundations",
    title: "The Official TypeScript Handbook (Strict Mode)",
    provider: "TypeScriptLang",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    format: "documentation",
    costType: "free",
    durationHours: 8,
    qualityScore: 0.95,
    languageOrDomainMatch: "TypeScript",
    description: "In-depth reference on generative typing, discrimination unions, and advanced utility types.",
  },
  {
    id: "res_fastify_mastery",
    skillId: "fastify_express",
    title: "High Performance Web APIs with Fastify",
    provider: "Fastify Official Guides",
    url: "https://fastify.dev/docs/latest/Guides/",
    format: "documentation",
    costType: "free",
    durationHours: 7,
    qualityScore: 0.93,
    description: "Fast JSON schema serialization, lifecycle hooks, and plugin architecture in Node.js.",
  },

  // Python / FastAPI
  {
    id: "res_fastapi_tutorial",
    skillId: "fastapi_framework",
    title: "FastAPI User Guide & Async Best Practices",
    provider: "Tiangolo / FastAPI",
    url: "https://fastapi.tiangolo.com/tutorial/",
    format: "interactive_course",
    costType: "free",
    durationHours: 10,
    qualityScore: 0.97,
    languageOrDomainMatch: "Python",
    description: "Step-by-step guide to building production asynchronous REST APIs with Pydantic validation.",
  },

  // DevOps & Cloud Infrastructure
  {
    id: "res_linux_networking_guide",
    skillId: "linux_networking_fundamentals",
    title: "Linux Server Administration & Networking Architecture",
    provider: "Linux Foundation & Red Hat Guides",
    url: "https://www.redhat.com/en/topics/linux",
    format: "documentation",
    costType: "free",
    durationHours: 10,
    qualityScore: 0.95,
    languageOrDomainMatch: "Linux / Networking",
    description: "Deep dive into Linux process model, systemd, TCP/IP sockets, iptables, and shell automation.",
  },
  {
    id: "res_docker_cicd_mastery",
    skillId: "docker_ci_cd",
    title: "Production Docker Containerization & GitHub Actions CI/CD",
    provider: "Docker Official Docs & GitHub Skills",
    url: "https://docs.docker.com/get-started/",
    format: "interactive_course",
    costType: "free",
    durationHours: 12,
    qualityScore: 0.96,
    languageOrDomainMatch: "Docker / CI/CD",
    description: "Multi-stage Docker builds, image minimization, container registries, and automated test pipelines.",
  },
  {
    id: "res_aws_cloud_infra",
    skillId: "cloud_deployment_aws",
    title: "Cloud Infrastructure as Code & Container Orchestration",
    provider: "AWS Architecture Center",
    url: "https://aws.amazon.com/architecture/",
    format: "documentation",
    costType: "free",
    durationHours: 14,
    qualityScore: 0.94,
    languageOrDomainMatch: "AWS / Cloud",
    description: "Deploying resilient container workloads, CloudFormation/Terraform IaC, VPC networking, and IAM.",
  },
  {
    id: "res_cis_hardening_benchmarks",
    skillId: "defensive_validation_hardening",
    title: "CIS Linux & Container Security Hardening Standards",
    provider: "Center for Internet Security (CIS)",
    url: "https://www.cisecurity.org/benchmark/",
    format: "documentation",
    costType: "free",
    durationHours: 8,
    qualityScore: 0.93,
    description: "Hardening Linux hosts, rootless Docker containers, kernel parameters, and automated compliance checks.",
  },

  // Full-Stack & Frontend
  {
    id: "res_modern_html_css",
    skillId: "html_css_modern_layouts",
    title: "Modern Responsive Web Design: CSS Grid, Flexbox & a11y",
    provider: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Learn/CSS",
    format: "documentation",
    costType: "free",
    durationHours: 8,
    qualityScore: 0.95,
    languageOrDomainMatch: "HTML / CSS",
    description: "Master modern responsive layouts, accessibility standards (WCAG), CSS variables, and mobile-first design.",
  },
  {
    id: "res_programming_fundamentals",
    skillId: "programming_fundamentals",
    title: "Computer Science Foundations & Problem Solving",
    provider: "Harvard CS50",
    url: "https://cs50.harvard.edu/",
    format: "interactive_course",
    costType: "free",
    durationHours: 12,
    qualityScore: 0.97,
    description: "Algorithmic thinking, memory models, control flow, functions, and structured problem decomposition.",
  },

  // Systems & C++
  {
    id: "res_cpp_memory_raii",
    skillId: "cpp_core_memory_management",
    title: "Modern C++ (C++17/20): RAII, Smart Pointers & Move Semantics",
    provider: "CppReference & ISO C++",
    url: "https://en.cppreference.com/w/cpp",
    format: "documentation",
    costType: "free",
    durationHours: 14,
    qualityScore: 0.96,
    languageOrDomainMatch: "Modern C++",
    description: "Master pointers, stack vs heap, RAII resource management, custom allocators, and move semantics.",
  },
  {
    id: "res_dsa_algorithms",
    skillId: "data_structures_algorithms",
    title: "High-Performance Data Structures & Algorithmic Complexity",
    provider: "MIT OpenCourseWare",
    url: "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/",
    format: "interactive_course",
    costType: "free",
    durationHours: 16,
    qualityScore: 0.96,
    description: "Trees, graphs, dynamic programming, asymptotic analysis, and cache-friendly data structures.",
  },

  // Defensive Cybersecurity
  {
    id: "res_cyber_ethics_sandbox",
    skillId: "authorized_lab_ethics",
    title: "Ethical Hacking Rules of Engagement & Isolated Lab Architecture",
    provider: "SANS Institute & NIST SP 800-115",
    url: "https://csrc.nist.gov/publications/detail/sp/800-115/final",
    format: "documentation",
    costType: "free",
    durationHours: 6,
    qualityScore: 0.95,
    languageOrDomainMatch: "Cybersecurity",
    description: "Legal boundaries (CFAA, ISO 27001), rules of engagement, and safe virtualization of isolated penetration testing subnets.",
  },
  {
    id: "res_cyber_packet_inspection",
    skillId: "linux_networking_fundamentals",
    title: "Wireshark Packet Analysis & Linux Network Auditing",
    provider: "Wireshark Foundation & Linux Documentation",
    url: "https://www.wireshark.org/docs/",
    format: "interactive_course",
    costType: "free",
    durationHours: 10,
    qualityScore: 0.94,
    languageOrDomainMatch: "Cybersecurity",
    description: "Deep dive into TCP handshake inspection, DNS tunneling detection, iptables firewalls, and socket auditing on Linux.",
  },
  {
    id: "res_owasp_top10_lab",
    skillId: "threat_modeling_owasp",
    title: "OWASP Top 10: Threat Identification & Remediation",
    provider: "OWASP Foundation",
    url: "https://owasp.org/www-project-top-ten/",
    format: "documentation",
    costType: "free",
    durationHours: 8,
    qualityScore: 0.96,
    languageOrDomainMatch: "Cybersecurity",
    description: "Understand root causes of modern web vulnerabilities and defensive countermeasures.",
  },
  {
    id: "res_secure_code_review_guide",
    skillId: "secure_code_review",
    title: "Secure Code Review & Static Analysis Methodology",
    provider: "OWASP Code Review Project",
    url: "https://owasp.org/www-project-code-review-guide/",
    format: "lab_environment",
    costType: "free",
    durationHours: 12,
    qualityScore: 0.93,
    languageOrDomainMatch: "Cybersecurity",
    description: "Techniques for auditing application source code and remediating flaws before production.",
  },
  {
    id: "res_web_sec_headers",
    skillId: "web_security_mechanisms",
    title: "Modern Web Security: CSP, HSTS, SameSite & Defense-in-Depth",
    provider: "MDN Web Security & OWASP",
    url: "https://developer.mozilla.org/en-US/docs/Web/Security",
    format: "documentation",
    costType: "free",
    durationHours: 8,
    qualityScore: 0.95,
    languageOrDomainMatch: "Cybersecurity",
    description: "Deep dive into Content Security Policy (CSP), HTTP Strict Transport Security, CORS security, and Subresource Integrity.",
  },
  {
    id: "res_vuln_scanning_tools",
    skillId: "vulnerability_scanning_tools",
    title: "Vulnerability Scanning & Automated Triage with OWASP ZAP",
    provider: "ZAP Community Guides",
    url: "https://www.zaproxy.org/getting-started/",
    format: "lab_environment",
    costType: "free",
    durationHours: 10,
    qualityScore: 0.92,
    languageOrDomainMatch: "Cybersecurity",
    description: "Automating dynamic application security testing (DAST) in isolated staging environments and interpreting CVSS scores.",
  },
  {
    id: "res_snort_traffic_analysis",
    skillId: "network_traffic_analysis",
    title: "Network Traffic Analysis & Snort/Suricata Rule Authoring",
    provider: "Suricata Community & SANS",
    url: "https://suricata.io/documentation/",
    format: "interactive_course",
    costType: "free",
    durationHours: 12,
    qualityScore: 0.94,
    languageOrDomainMatch: "Cybersecurity",
    description: "Writing signature-based intrusion detection rules, analyzing anomalous PCAP captures, and detecting reconnaissance scans.",
  },
  {
    id: "res_defensive_hardening",
    skillId: "defensive_validation_hardening",
    title: "Linux & Application Hardening via CIS Benchmarks",
    provider: "Center for Internet Security (CIS)",
    url: "https://www.cisecurity.org/cis-benchmarks",
    format: "documentation",
    costType: "free",
    durationHours: 8,
    qualityScore: 0.96,
    languageOrDomainMatch: "Cybersecurity",
    description: "Implementing least-privilege host configurations, disabling unnecessary capabilities, and configuring auditd profiles.",
  },
  {
    id: "res_ctf_defense_methodology",
    skillId: "ctf_lab_methodology",
    title: "Defensive CTF Methodology & Threat Incident Post-Mortems",
    provider: "OverTheWire & TryHackMe Defense",
    url: "https://overthewire.org/wargames/",
    format: "lab_environment",
    costType: "free",
    durationHours: 14,
    qualityScore: 0.95,
    languageOrDomainMatch: "Cybersecurity",
    description: "Structured challenge resolution, defense-in-depth verification, and clear post-mortem incident documentation.",
  },
];

// ==========================================
// 5. CURATED PRACTICAL PROJECTS
// ==========================================

export const SEEDED_PROJECTS: PracticalProject[] = [
  // DevOps & Cloud Platform Infrastructure
  {
    id: "proj_devops_ci_cd_pipeline",
    title: "Automated Multi-Stage CI/CD Pipeline & Containerized Deployment",
    description:
      "Design and implement an automated GitOps CI/CD pipeline with GitHub Actions, building hardened multi-stage Docker images, running automated test suites, and deploying to Cloud infrastructure.",
    targetSkillIds: ["docker_ci_cd", "linux_networking_fundamentals", "cloud_deployment_aws", "unit_integration_testing"],
    deliverables: [
      "Multi-stage Dockerfile producing a minimal secure production container (<50MB)",
      "GitHub Actions CI pipeline running lint, unit tests, and vulnerability scans (Trivy)",
      "Automated deployment workflow to cloud environment with rollback capabilities",
      "Docker Compose staging environment with health checks and log aggregation",
    ],
    verificationChecklist: [
      "CI pipeline automatically triggers on pull request and passes branch protection rules",
      "Vulnerability scan reports 0 critical/high CVEs in production container image",
      "Zero-downtime rolling deployment verified in staging environment",
    ],
    estimatedHours: 18,
    domainContext: "Cloud Infrastructure & Platform Engineering",
  },
  {
    id: "proj_devops_infra_hardening",
    title: "Cloud Platform Infrastructure as Code & Security Hardening",
    description:
      "Provision production-ready cloud infrastructure using Terraform / CloudFormation, enforcing CIS benchmark hardening, IAM least-privilege, and automated container orchestration.",
    targetSkillIds: ["cloud_deployment_aws", "defensive_validation_hardening", "linux_networking_fundamentals"],
    deliverables: [
      "Modular Infrastructure as Code (IaC) templates for VPC, subnets, and container clusters",
      "Automated security hardening script enforcing CIS Level 1 benchmarks",
      "Prometheus & Grafana monitoring dashboard tracking latency and container metrics",
    ],
    verificationChecklist: [
      "IaC plan applies cleanly with zero manual cloud console interventions",
      "All IAM policies adhere to strict principle of least privilege",
    ],
    estimatedHours: 20,
    domainContext: "DevOps & Cloud Security",
  },

  // Full-Stack Web & Applications
  {
    id: "proj_fullstack_saas_app",
    title: "Full-Stack SaaS Task Management & Collaboration Platform",
    description:
      "Build an end-to-end full-stack web application with React/Next.js frontend, TypeScript backend API, PostgreSQL relational database, and JWT authentication.",
    targetSkillIds: ["html_css_modern_layouts", "typescript_foundations", "rest_api_design", "sql_relational_modeling", "jwt_oauth_security"],
    deliverables: [
      "Responsive React/Next.js frontend with modern CSS Grid/Flexbox and dark mode",
      "Type-safe REST API handling CRUD operations with strict validation",
      "PostgreSQL relational database schema with migration scripts",
      "Automated end-to-end and component test suite",
    ],
    verificationChecklist: [
      "Lighthouse accessibility and performance score >90",
      "Type-safe end-to-end contract between client and API with zero any types",
    ],
    estimatedHours: 20,
    domainContext: "Full-Stack Web Software",
  },

  // Systems & Modern C++
  {
    id: "proj_cpp_concurrent_engine",
    title: "High-Performance Concurrent Memory-Safe Packet Processing Engine",
    description:
      "Architect a multithreaded network packet processing engine in Modern C++ leveraging lock-free queues, RAII memory management, and SIMD optimizations.",
    targetSkillIds: ["cpp_core_memory_management", "data_structures_algorithms", "linux_networking_fundamentals"],
    deliverables: [
      "Modern C++20 engine with zero memory leaks verified via Valgrind / AddressSanitizer",
      "Lock-free circular buffer and thread pool implementation",
      "Benchmark suite measuring throughput (>1M packets/sec)",
    ],
    verificationChecklist: [
      "Zero memory leaks or undefined behavior detected by AddressSanitizer",
      "High-throughput sustained benchmark under multi-core load",
    ],
    estimatedHours: 22,
    domainContext: "Systems & Low-Latency Architecture",
  },

  // Java & Enterprise ERP
  {
    id: "proj_java_inventory_api",
    title: "Spring Boot Inventory & Order REST Service",
    description:
      "Develop a fully tested Spring Boot microservice managing warehouse stock, product catalog, and order placement with relational integrity.",
    targetSkillIds: ["spring_boot_core", "spring_data_jpa", "sql_relational_modeling", "unit_integration_testing"],
    deliverables: [
      "REST API with GET /products, POST /orders with stock reservation",
      "Flyway SQL migrations creating 3NF normalized tables",
      "Integration test suite with Testcontainers (PostgreSQL)",
      "OpenAPI 3.1 Swagger UI documentation",
    ],
    verificationChecklist: [
      "Concurrent order placements do not oversell inventory (SELECT FOR UPDATE / isolation)",
      "Zero N+1 query logs during batch retrieval",
      ">80% branch test coverage",
    ],
    estimatedHours: 16,
    domainContext: "Enterprise ERP / Logistics",
  },
  {
    id: "proj_java_erp_workflow",
    title: "Enterprise ERP Purchase Order State Machine & Audit Ledger",
    description:
      "Construct a multi-stage approval state machine (Draft -> Submitted -> Approved -> Fulfilled -> Invoiced) with immutable audit events and RBAC.",
    targetSkillIds: ["erp_state_machine_workflows", "enterprise_security_auth", "database_migrations"],
    deliverables: [
      "State transition engine preventing invalid order states",
      "Spring Security OAuth2 JWT role authorization (Purchaser vs Manager vs Auditor)",
      "Immutable audit log capturing every state change with actor and timestamp",
      "Docker Compose environment containing API, PostgreSQL, and mock identity provider",
    ],
    verificationChecklist: [
      "Non-manager cannot execute approval endpoint (returns 403 Forbidden)",
      "Audit trail records all mutations without data loss",
      "Re-entrant transitions reject invalid states with RFC 7807 problem details",
    ],
    estimatedHours: 24,
    domainContext: "Enterprise ERP & Financial Auditing",
  },

  // Node.js & TypeScript
  {
    id: "proj_node_saas_api",
    title: "Modular SaaS API with Fastify & Prisma",
    description:
      "Build a high-performance SaaS backend with JWT session rotation, rate limiting, and multi-tenant organization boundaries.",
    targetSkillIds: ["typescript_foundations", "fastify_express", "prisma_drizzle_orm", "jwt_oauth_security"],
    deliverables: [
      "Fastify server with Ajv request schema validation",
      "Prisma schema with multi-tenant Organization and User entities",
      "Redis-backed token blocklist and sliding-window rate limiter",
    ],
    verificationChecklist: [
      "Tenant A cannot read data belonging to Tenant B",
      "Rate limit returns HTTP 429 when threshold exceeded",
      "100% strict TypeScript types with no `any` leaks",
    ],
    estimatedHours: 16,
    domainContext: "Modern SaaS Product",
  },

  // Python & FastAPI
  {
    id: "proj_python_async_service",
    title: "High-Throughput Async Data Ingestion Service",
    description:
      "Architect a FastAPI asynchronous pipeline that validates incoming JSON telemetry streams, stores normalized events in PostgreSQL, and enqueues tasks.",
    targetSkillIds: ["fastapi_framework", "asyncio_concurrency", "sqlalchemy_alembic", "pydantic_validation"],
    deliverables: [
      "FastAPI endpoint handling async batch ingestion",
      "Pydantic V2 models parsing and sanitizing payloads",
      "Async SQLAlchemy session with connection pooling",
      "Pytest test suite with async fixtures",
    ],
    verificationChecklist: [
      "Benchmark sustains >1,000 req/sec on local hardware without blocking event loop",
      "Malformed telemetry payload yields clear 422 error details",
    ],
    estimatedHours: 14,
    domainContext: "Cloud Data Services",
  },

  // Defensive Cybersecurity
  {
    id: "proj_cyber_sandbox_lab",
    title: "Isolated Ethical Lab Setup & Packet Analysis",
    description:
      "Establish an isolated virtualization sandbox environment, configure firewall boundary rules, and perform deep Wireshark packet capture analysis on simulated network traffic.",
    targetSkillIds: ["authorized_lab_ethics", "linux_networking_fundamentals"],
    deliverables: [
      "Vagrant/Docker isolated host-only network configuration with verified egress controls",
      "Wireshark packet capture PCAP report identifying cleartext credentials and port scan signatures",
      "Hardened iptables baseline ruleset blocking unauthorized inbound probe vectors",
    ],
    verificationChecklist: [
      "All lab interfaces isolated with zero leakage to public network",
      "Network capture accurately tags 3 simulated anomaly patterns",
    ],
    estimatedHours: 14,
    domainContext: "Defensive Security Engineering",
  },
  {
    id: "proj_cyber_lab_audit",
    title: "Defensive Security Audit, OWASP Analysis & Secure Code Remediation",
    description:
      "Audit a vulnerable web application in an isolated lab, produce a STRIDE threat model, remediate code flaws (SAST/DAST), and verify hardened HTTP headers.",
    targetSkillIds: ["threat_modeling_owasp", "secure_code_review", "web_security_mechanisms"],
    deliverables: [
      "STRIDE threat model document identifying key entry vectors and mitigation matrix",
      "Remediated source code eliminating SQL injection, XSS, and broken access controls",
      "Hardened CSP and security header configuration achieving A+ rating",
      "Defensive post-audit verification report",
    ],
    verificationChecklist: [
      "All automated SAST warnings resolved",
      "Security header scanner returns A+ grade",
      "All exercises confirmed within authorized sandbox scope",
    ],
    estimatedHours: 18,
    domainContext: "Defensive Security Engineering",
  },
  {
    id: "proj_cyber_ctf_defense",
    title: "Vulnerability Scanning, IDS Detection Rules & Defensive CTF Lab",
    description:
      "Conduct automated vulnerability assessment with OWASP ZAP, author custom Snort/Suricata network intrusion detection rules, enforce CIS hardening, and solve defensive CTF scenarios.",
    targetSkillIds: [
      "vulnerability_scanning_tools",
      "network_traffic_analysis",
      "defensive_validation_hardening",
      "ctf_lab_methodology",
    ],
    deliverables: [
      "Prioritized CVSS vulnerability assessment report with proof-of-concept validations",
      "Custom Snort/Suricata ruleset matching suspicious reconnaissance beacons",
      "CIS benchmark automated audit script verifying Linux host compliance",
      "Defensive CTF completion writeups detailing root cause remediation",
    ],
    verificationChecklist: [
      "Intrusion detection rule triggers 100% true-positive alerts on test traffic",
      "Zero critical/high vulnerabilities remaining on hardened host",
      "Post-mortem writeups completed for 3 defensive challenge scenarios",
    ],
    estimatedHours: 22,
    domainContext: "Defensive Security Engineering",
  },
];
